language: scala
jdk:
- oraclejdk8

branches:
  only:
    - master

before_install:
  - git fetch --tags

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.0/0.4.0-12-102ddf && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill --version

sudo: false
